<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove=".github1\**" />
		<Content Remove=".github1\**" />
		<EmbeddedResource Remove=".github1\**" />
		<None Remove=".github1\**" />
	</ItemGroup>

	<ItemGroup>
		<None Include="C:\Users\busra\Desktop\ZiraatApi\ZiraatAPI\.github\workflows\ci-cd.yml" Link="ci-cd.yml" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include=".github\workflows\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>
</Project>